config/routes.rb
DemoApp::Application.routes.draw do
  resources :micropos

  resources :users

end

app/models/micropo.rb
class Micropo < ActiveRecord::Base
 belongs_to :user  
 validates :content, length: { maximum: 140 }
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :micropos
	has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/micropos_controller.rb
class MicroposController < ApplicationController
  # GET /micropos
  # GET /micropos.json
  def index
    @micropos = Micropo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micropos }
    end
  end

  # GET /micropos/1
  # GET /micropos/1.json
  def show
    @micropo = Micropo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropo }
    end
  end

  # GET /micropos/new
  # GET /micropos/new.json
  def new
    @micropo = Micropo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropo }
    end
  end

  # GET /micropos/1/edit
  def edit
    @micropo = Micropo.find(params[:id])
  end

  # POST /micropos
  # POST /micropos.json
  def create
    @micropo = Micropo.new(params[:micropo])

    respond_to do |format|
      if @micropo.save
        format.html { redirect_to @micropo, notice: 'Micropo was successfully created.' }
        format.json { render json: @micropo, status: :created, location: @micropo }
      else
        format.html { render action: "new" }
        format.json { render json: @micropo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /micropos/1
  # PUT /micropos/1.json
  def update
    @micropo = Micropo.find(params[:id])

    respond_to do |format|
      if @micropo.update_attributes(params[:micropo])
        format.html { redirect_to @micropo, notice: 'Micropo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micropos/1
  # DELETE /micropos/1.json
  def destroy
    @micropo = Micropo.find(params[:id])
    @micropo.destroy

    respond_to do |format|
      format.html { redirect_to micropos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micropos_helper.rb
module MicroposHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/micropos/_form.html.erb
<%= form_for(@micropo) do |f| %>
  <% if @micropo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropo.errors.count, "error") %> prohibited this micropo from being saved:</h2>

      <ul>
      <% @micropo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micropos/edit.html.erb
<h1>Editing micropo</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropo %> |
<%= link_to 'Back', micropos_path %>

app/views/micropos/index.html.erb
<h1>Listing micropos</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micropos.each do |micropo| %>
  <tr>
    <td><%= micropo.content %></td>
    <td><%= micropo.user_id %></td>
    <td><%= link_to 'Show', micropo %></td>
    <td><%= link_to 'Edit', edit_micropo_path(micropo) %></td>
    <td><%= link_to 'Destroy', micropo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropo', new_micropo_path %>

app/views/micropos/new.html.erb
<h1>New micropo</h1>

<%= render 'form' %>

<%= link_to 'Back', micropos_path %>

app/views/micropos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropo.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropo.user_id %>
</p>


<%= link_to 'Edit', edit_micropo_path(@micropo) %> |
<%= link_to 'Back', micropos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>